title: "Mumuste Mend"
email: mumuste.mend@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 this is my new insane site to try the mlh and github make personal page feed.xml site description.
baseurl: "/" 
url: "/portfolio-template" 
github_username:  mumuste21mend 

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
